name: CI/CD for test page 

on:
  push:
    branches:
      - develop

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4  
      with:
        ref: develop
        # working-directory: /opt/instantRelocate/Coworking/

    # - name: pullRepo
    #   run: git pull
    #   working-directory: /opt/instantRelocate/Coworking/

    - name: Install dependencies
      run: npm ci
      # working-directory: /opt/instantRelocate/Coworking/

    - name: Build
      run: npm run build
      # working-directory: /opt/instantRelocate/Coworking/

    - name: Deploy
      uses: easingthemes/ssh-deploy@v2.1.5
      env: 

        SSH_PRIVATE_KEY: ${{ secrets.RELOCATE_SSH }}
        SOURCE: '/opt/instantRelocate/Coworking/dist/'
        REMOTE_HOST: ${{ secrets.TEST_HOST }}
        REMOTE_USER: ${{ secrets.SERVER_USER }}
        TARGET: '/opt/instantRelocate/Coworking/'